sudo: false
language: ruby
rvm:
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
before_install:
  - wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
  - sudo dpkg -i puppetlabs-release-trusty.deb
  - sudo apt-get update
script:
  - make ci
